services:
  langfuse-worker:
    image: docker.io/langfuse/langfuse-worker:3
    restart: always
    depends_on:
      langfuse-db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    env_file: .env.langfuse

  langfuse-web:
    image: docker.io/langfuse/langfuse:3
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      langfuse-db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    env_file: .env.langfuse

  langfuse-db:
    image: postgres:15-alpine
    env_file: .env.langfuse
    volumes:
      - langfuse_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse"]
      interval: 5s
      retries: 10
    restart: always

  clickhouse:
    image: docker.io/clickhouse/clickhouse-server
    env_file: .env.langfuse
    restart: always
    user: "101:101"
    environment:
      CLICKHOUSE_DB: default
    volumes:
      - langfuse_clickhouse_data:/var/lib/clickhouse
      - langfuse_clickhouse_logs:/var/log/clickhouse-server
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s

  minio:
    image: cgr.dev/chainguard/minio
    env_file: .env.langfuse
    restart: always
    entrypoint: sh
    command: -c 'mkdir -p /data/langfuse && minio server --address ":9000" --console-address ":9001" /data'
    ports:
      - "127.0.0.1:9090:9000"
      - "127.0.0.1:9091:9001"
    volumes:
      - langfuse_minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s

  redis:
    image: docker.io/redis:7
    env_file: .env.langfuse
    restart: always
    command:
      - /bin/sh
      - -ec
      - 'exec redis-server --requirepass "$$REDIS_AUTH" --maxmemory-policy noeviction'
    volumes:
      - langfuse_redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", 'redis-cli -a "$$REDIS_AUTH" ping']
      interval: 3s
      timeout: 10s
      retries: 10

volumes:
  langfuse_db_data:
  langfuse_clickhouse_data:
  langfuse_clickhouse_logs:
  langfuse_minio_data:
  langfuse_redis_data:
